const $=x=>document.getElementById(x);
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let editing=null;
const money=(n,c='৳')=>c+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const toast=(t,type='success')=>{let x=$('toast');x.textContent=t;x.className='show '+type;setTimeout(()=>x.className='',2500)};
function nav(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(p).classList.add('active');document.querySelectorAll('aside button[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('title').textContent={dashboard:'Dashboard',create:'Create Invoice',invoices:'All Invoices',taxes:'Tax Manager',settings:'Settings',about:'About'}[p];if(p==='dashboard')dashboard();if(p==='invoices')invoices();if(p==='taxes')taxRender();if(p==='settings')loadSettings();if(p==='create')taxChecks()}
document.querySelectorAll('aside button[data-page]').forEach(b=>b.onclick=()=>{nav(b.dataset.page);if(window.innerWidth<=750)$('sidebar').classList.remove('open')});$('menu').onclick=()=>$('sidebar').classList.add('open');$('closeMenu').onclick=()=>$('sidebar').classList.remove('open');$('sidebarOverlay').onclick=()=>$('sidebar').classList.remove('open');
function clock(){let d=new Date();$('date').textContent=d.getDate();$('month').textContent=d.toLocaleDateString('en-US',{month:'long',year:'numeric'});$('day').textContent=d.toLocaleDateString('en-US',{weekday:'long'});$('time').textContent=d.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true})}clock();setInterval(clock,1000);
function addItem(x={name:'',qty:1,price:0}){let tr=document.createElement('tr');tr.innerHTML=`<td><input class="n" value="${x.name||''}"></td><td><input class="q" type="number" min="1" value="${x.qty||1}"></td><td><input class="p" type="number" min="0" value="${x.price||0}"></td><td class="t">৳0.00</td><td><button>✕</button></td>`;tr.querySelectorAll('input').forEach(i=>i.oninput=calc);tr.querySelector('button').onclick=()=>{tr.remove();calc()};$('items').appendChild(tr);calc()}$('addItem').onclick=()=>addItem();
function taxChecks(sel=[]){let ts=get('taxes',[]);$('taxChecks').innerHTML=ts.map(t=>`<label class="taxcheck"><input type="checkbox" value="${t.id}" ${sel.includes(t.id)?'checked':''}> ${t.name} (${t.rate}%)</label>`).join('')||'No tax added';document.querySelectorAll('#taxChecks input').forEach(x=>x.onchange=calc)}
function calc(){let sub=0;$('items').querySelectorAll('tr').forEach(r=>{let q=+r.querySelector('.q').value||0,p=+r.querySelector('.p').value||0,v=q*p;sub+=v;r.querySelector('.t').textContent=money(v,$('currency').value)});let discount=+($('discount').value||0),base=Math.max(0,sub-discount),ts=get('taxes',[]),selected=[...document.querySelectorAll('#taxChecks input:checked')].map(x=>ts.find(t=>t.id==x.value)),applied=selected.map(t=>({...t,amount:base*t.rate/100})),tax=applied.reduce((a,t)=>a+t.amount,0),grand=base+tax;$('subtotal').textContent=money(sub,$('currency').value);$('taxRows').innerHTML=applied.map(t=>`<div>${t.name} (${t.rate}%) <b>${money(t.amount,$('currency').value)}</b></div>`).join('');$('grand').textContent=money(grand,$('currency').value);return{sub,discount,applied,grand}}$('discount').oninput=calc;$('currency').onchange=calc;
function form(){let c=calc(),items=[...$('items').querySelectorAll('tr')].map(r=>({name:r.querySelector('.n').value,qty:+r.querySelector('.q').value,price:+r.querySelector('.p').value})).filter(x=>x.name);return{id:editing||Date.now(),number:$('number').value,date:$('invoiceDate').value,due:$('due').value,currency:$('currency').value,customer:{name:$('cname').value,phone:$('cphone').value,email:$('cemail').value,address:$('caddress').value},items,discount:c.discount,sub:c.sub,taxes:c.applied,grand:c.grand,payment:{method:$('payMethod').value,status:$('payStatus').value,reference:$('payRef').value},shipping:{name:$('shipName').value,phone:$('shipPhone').value,address:$('shipAddress').value,courier:$('courier').value,tracking:$('tracking').value}}}
function saveInv(print=false){let i=form();if(!i.customer.name||!i.items.length)return toast('Customer and item required','error');let a=get('invoices',[]),n=a.findIndex(x=>x.id===i.id);n>=0?a[n]=i:a.unshift(i);set('invoices',a);toast('Invoice saved successfully');editing=null;if(print)setTimeout(()=>printInvoice(i),400);else {reset();nav('invoices')}}$('save').onclick=()=>saveInv();$('savePrint').onclick=()=>saveInv(true);
function reset(){editing=null;$('number').value='INV-'+String(get('invoices',[]).length+1).padStart(4,'0');$('invoiceDate').value=new Date().toISOString().slice(0,10);['due','cname','cphone','cemail','caddress','payRef','shipName','shipPhone','shipAddress','courier','tracking'].forEach(x=>$(x).value='');$('discount').value=0;$('items').innerHTML='';addItem();taxChecks()}$('clear').onclick=reset;
function taxRender(){let a=get('taxes',[]);$('taxList').innerHTML=a.map(t=>`<p><b>${t.name}</b> — ${t.rate}% <button onclick="delTax(${t.id})">Delete</button></p>`).join('')||'No taxes'}$('addTax').onclick=()=>{let n=$('taxName').value,r=+$('taxRate').value;if(!n)return toast('Tax name required','error');let a=get('taxes',[]);a.push({id:Date.now(),name:n,rate:r});set('taxes',a);$('taxName').value='';$('taxRate').value='';taxRender();toast('Tax added')};window.delTax=id=>{set('taxes',get('taxes',[]).filter(x=>x.id!==id));taxRender()};
function invoices(){let a=get('invoices',[]),q=$('search').value.toLowerCase();a=a.filter(i=>(i.number+i.customer.name).toLowerCase().includes(q));$('invoiceList').innerHTML=a.map(i=>`<tr><td>${i.number}</td><td>${i.customer.name}</td><td>${i.date}</td><td>${i.payment.method}<br><small>${i.payment.status}</small></td><td>${money(i.grand,i.currency)}</td><td><button onclick="edit(${i.id})">Edit</button><button onclick="printBy(${i.id})">Print</button><button onclick="label(${i.id})">Shipping Label</button><button onclick="del(${i.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No invoices</td></tr>'}$('search').oninput=invoices;
window.del=id=>{set('invoices',get('invoices',[]).filter(x=>x.id!==id));invoices()};window.edit=id=>{let i=get('invoices',[]).find(x=>x.id===id);editing=id;$('number').value=i.number;$('invoiceDate').value=i.date;$('due').value=i.due||'';$('currency').value=i.currency;$('cname').value=i.customer.name;$('cphone').value=i.customer.phone;$('cemail').value=i.customer.email;$('caddress').value=i.customer.address;$('payMethod').value=i.payment.method;$('payStatus').value=i.payment.status;$('payRef').value=i.payment.reference;$('shipName').value=i.shipping.name;$('shipPhone').value=i.shipping.phone;$('shipAddress').value=i.shipping.address;$('courier').value=i.shipping.courier;$('tracking').value=i.shipping.tracking;$('discount').value=i.discount;$('items').innerHTML='';i.items.forEach(addItem);taxChecks(i.taxes.map(t=>t.id));calc();nav('create')};
function qr(i){let text=encodeURIComponent(JSON.stringify({invoice:i.number,customer:i.customer.name,total:i.grand}));return 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data='+text}
function biz(){return get('business',{})}
function printInvoice(i){
let b=biz(),
rows=i.items.map(x=>`<tr><td>${x.name}</td><td>${x.qty}</td><td>${money(x.price,i.currency)}</td><td>${money(x.qty*x.price,i.currency)}</td></tr>`).join(''),
w=window.open('');
if(!w){toast('Please allow popups for printing','error');return;}
w.document.write(`<html><head><title>${i.number}</title><style>
@page{margin:12mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#1d3557;margin:0;background:#fff}
.invoice{max-width:850px;margin:auto}.head{display:flex;justify-content:space-between;align-items:flex-start;padding-bottom:20px;border-bottom:4px solid #457b9d}
.brand{display:flex;gap:15px;align-items:flex-start}.brand img{max-width:85px;max-height:70px;object-fit:contain}.brand h1{margin:0 0 7px;font-size:27px}.muted{font-size:12px;color:#555;line-height:1.6}
.invoice-info{text-align:right}.invoice-info h2{margin:0;color:#457b9d;font-size:25px}.invoice-no{font-size:16px;font-weight:bold;margin:7px 0}
.qr-box{margin-top:10px;display:inline-block;padding:7px;border:1px solid #ddd;border-radius:8px;text-align:center}.qr-box img{width:110px;height:110px;display:block}.qr-box span{font-size:9px;color:#777}
.addresses{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:25px 0}.box{background:#f5f8fa;padding:15px;border-radius:10px;border-left:4px solid #457b9d}.box h3{margin:0 0 8px;font-size:13px;color:#457b9d;text-transform:uppercase}
table{width:100%;border-collapse:collapse;margin-top:15px}th{background:#1d3557;color:#fff;padding:11px;text-align:left}td{padding:11px;border-bottom:1px solid #ddd}tr:nth-child(even){background:#fafafa}
.bottom{display:grid;grid-template-columns:1fr 320px;gap:25px;margin-top:20px}.payment{padding:15px;border-radius:10px;background:#f5f8fa}.payment h3{margin-top:0;color:#457b9d}.total{padding:15px;border:1px solid #ddd;border-radius:10px}.total div{display:flex;justify-content:space-between;padding:6px 0}.grand{font-size:19px;border-top:2px solid #1d3557;margin-top:6px;padding-top:10px;color:#1d3557}
.footer{text-align:center;margin-top:30px;padding-top:15px;border-top:1px dashed #aaa;font-size:11px;color:#777}
@media print{body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style></head><body><div class="invoice">
<div class="head"><div class="brand">${b.logo?`<img src="${b.logo}">`:''}<div><h1>${b.name||'Your Business'}</h1><div class="muted">${b.address||''}<br>${b.phone||''}${b.email?'<br>'+b.email:''}${b.license?'<br>License: '+b.license:''}</div></div></div>
<div class="invoice-info"><h2>INVOICE</h2><div class="invoice-no">${i.number}</div><div class="muted">Date: ${i.date||''}<br>Due: ${i.due||''}</div><div class="qr-box"><img src="${qr(i)}"><span>Scan Invoice QR</span></div></div></div>
<div class="addresses"><div class="box"><h3>Bill To</h3><b>${i.customer.name||''}</b><br>${i.customer.address||''}<br>${i.customer.phone||''}<br>${i.customer.email||''}</div><div class="box"><h3>Shipping To</h3><b>${(i.shipping||{}).name||i.customer.name||''}</b><br>${(i.shipping||{}).address||i.customer.address||''}<br>${(i.shipping||{}).phone||i.customer.phone||''}</div></div>
<table><tr><th>Item Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>${rows}</table>
<div class="bottom"><div class="payment"><h3>Payment Information</h3><b>Method:</b> ${i.payment.method||'-'}<br><b>Status:</b> ${i.payment.status||'-'}<br><b>Reference:</b> ${i.payment.reference||'-'}</div><div class="total"><div>Subtotal <b>${money(i.sub,i.currency)}</b></div>${i.taxes.map(t=>`<div>${t.name} (${t.rate}%) <b>${money(t.amount,i.currency)}</b></div>`).join('')}<div>Discount <b>${money(i.discount||0,i.currency)}</b></div><div class="grand"><b>Grand Total</b><b>${money(i.grand,i.currency)}</b></div></div></div>
<div class="footer">Thank you for your business • ${i.number}</div></div></body></html>`);
w.document.close();setTimeout(()=>w.print(),700)
}
window.printBy=id=>printInvoice(get('invoices',[]).find(x=>x.id===id));
function printLabel(i){let b=biz(),s=i.shipping||{},name=s.name||i.customer.name,address=s.address||i.customer.address,phone=s.phone||i.customer.phone,w=window.open('');w.document.write(`<style>@page{size:100mm 150mm;margin:0}html,body{width:100%;height:100%;margin:0}body{font-family:Arial;display:flex;justify-content:center;align-items:center}.label{box-sizing:border-box;width:90mm;min-height:135mm;border:3px solid #111;padding:14px;position:relative}.top{border-bottom:2px dashed #222;padding-bottom:10px;font-size:12px}.title{font-size:22px;font-weight:bold}.from,.to{margin-top:16px}.to{font-size:19px}.qr{width:145px;height:145px;position:absolute;right:14px;bottom:14px}.track{font-weight:bold;margin-top:12px}@media print{body{display:flex!important;justify-content:center!important;align-items:center!important}.label{margin:auto!important}}</style><div class="label"><div class="top"><div class="title">SHIPPING LABEL</div>Invoice: ${i.number}</div><div class="from"><b>FROM:</b><br>${b.name||'Your Business'}<br>${b.address||''}<br>${b.phone||''}</div><div class="to"><b>SHIP TO:</b><br>${name}<br>${address}<br>${phone}</div><div class="track">TRACKING: ${s.tracking||i.number}</div><div>Courier: ${s.courier||'-'}</div><div>Payment: ${i.payment.method} / ${i.payment.status}</div><img class="qr" src="${qr(i)}"></div>`);w.document.close();setTimeout(()=>w.print(),700)}
window.label=id=>printLabel(get('invoices',[]).find(x=>x.id===id));
function dashboard(){let a=get('invoices',[]),sales=a.reduce((s,x)=>s+x.grand,0),m=new Date().toISOString().slice(0,7),ms=a.filter(x=>(x.date||'').startsWith(m)).reduce((s,x)=>s+x.grand,0);$('sInv').textContent=a.length;$('sSales').textContent=money(sales);$('sMonth').textContent=money(ms);$('sCustomers').textContent=new Set(a.map(x=>x.customer.name)).size;$('recent').innerHTML=a.slice(0,5).map(x=>`${x.number} — ${x.customer.name} — ${money(x.grand,x.currency)}<br>`).join('')||'No invoices yet.'}
$('csv').onclick=()=>{let a=get('invoices',[]),rows=[['Invoice','Customer','Date','Payment','Total'],...a.map(i=>[i.number,i.customer.name,i.date,i.payment.method,i.grand])];download('InvoiceFlow.csv','text/csv',rows.map(r=>r.join(',')).join('\n'))};$('json').onclick=()=>download('InvoiceFlow_Backup.json','application/json',JSON.stringify(get('invoices',[]),null,2));function download(n,t,c){let u=URL.createObjectURL(new Blob([c],{type:t})),a=document.createElement('a');a.href=u;a.download=n;a.click()}
function loadSettings(){let b=biz();$('bizName').value=b.name||'';$('license').value=b.license||'';$('bizPhone').value=b.phone||'';$('bizEmail').value=b.email||'';$('bizAddress').value=b.address||'';$('logoPreview').innerHTML=b.logo?'<img src="'+b.logo+'" style="max-width:100px">':''}
$('logo').onchange=e=>{let r=new FileReader();r.onload=()=>{$('logoPreview').dataset.logo=r.result;$('logoPreview').innerHTML='<img src="'+r.result+'" style="max-width:100px">'};if(e.target.files[0])r.readAsDataURL(e.target.files[0])};$('saveBiz').onclick=()=>{let old=biz();set('business',{name:$('bizName').value,license:$('license').value,phone:$('bizPhone').value,email:$('bizEmail').value,address:$('bizAddress').value,logo:$('logoPreview').dataset.logo||old.logo||''});toast('Business settings saved')};$('saveLayout').onclick=()=>{set('layout',{pageSize:$('pageSize').value,orientation:$('orientation').value,layout:$('layout').value,accent:$('accent').value});toast('Page setup saved')};
reset();dashboard();
